apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: traefik-role-binding
    patch: |-
      - op: add
        path: /subjects/0/namespace
        value: traefik
  - target:
      kind: Service
      name: traefik-web
    patch: |-
      - op: add
        path: /metadata/annotations/metallb.universe.tf\/loadBalancerIPs
        value: 192.168.5.201