apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
    kind: IngressRoute
  patch: |-
    - op: add
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
      value: 192.168.5.201