apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-lb-iprange
  namespace: metallb-system
spec:
  addresses:
  - 192.168.5.200-192.168.5.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system