apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.5.202
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`traefik.example.com`)
      services:
        - kind: TraefikService
          name: traefik-dashboard