apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
- apiGroups: ["traefik.containo.us","traefik.io"]
  resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.14.0
          args:
            - --source=traefik-proxy
            - --provider=webhook
            - --webhook-provider-url=http://localhost:8888
          resources: 
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "50m"
              memory: "50Mi"
        - name: adguardhome-provider
          image: ghcr.io/muhlba91/external-dns-provider-adguard:v3.1.0
          env:
            - name: LOG_LEVEL
              value: debug
            - name: ADGUARD_HOME
              value: "http://adguard-web.adguard.svc.cluster.local/control/" # Note: URL should be in the format of http://adguard.home:3000/control/
            - name: ADGUARD_PASSWORD
              value: "external-password"
            - name: ADGUARD_USER
              value: "external"
          resources: 
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "50m"
              memory: "50Mi"