apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"
spec:
  selector:
    app: adguard
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
    name: dns
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"
spec:
  selector:
    app: adguard
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-web
spec:
  selector:
    app: adguard
  ports:
  - port: 80
    targetPort: 80
    name: http
