apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml

patches:
  - target:
    kind: IngressRoute
    name: adguard-dashboard
  patch: |-
    - op: add
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
      value: 192.168.5.201