apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - path: svc-external-ip.yaml
    target:
      kind: Service
      annotationSelector: external-service=dns