apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      kind: Service
      annotationSelector: external-service=dns
    patch: |-
      - op: add
        path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
        value: 192.168.5.200
  
  - target:
      kind: IngressRoute
    patch: |-
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: 192.168.5.201