apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`longhorn.example.com`)
      services:
        - kind: TraefikService
          name: longhorn-frontend
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: longhorn-frontend
spec:
  weighted:
    services:
      - name: longhorn-frontend
        port: 80
        weight: 1