apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`longhorn.example.com`)
      services:
        - kind: Service
          name: longhorn-frontend
          port: 80